version: '2.1'
services:
  postgres:
    image: kartoza/postgis:12.0
    ports:
      - 5432:5432
    container_name: community-board-db-postgres
    env_file:
      - .env
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5
  server:
    build: ./server
    ports:
      - 5000:5000
    volumes:
      - ./server/src:/server/src
    container_name: community-board-db-server
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env
